on:
  push:
  workflow_dispatch:

jobs:
  aws-cloudformation-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - shell: pwsh
        run: Install-Module -Name AWS.Tools.CloudFormation -Force
      - run: pwsh -File deploy.ps1
